#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Render an Ansible YAML inventory from `tofu output -json`.

Consumes stdin (or a file path argument) and prints inventory YAML to stdout.
Stdlib only -- no PyYAML, hand-emitted YAML so we don't need a venv.

Expected Tofu outputs (from terraform/environments/do-test/outputs.tf):
  - cp_nodes      : list({ name, public_ip, private_ip, id })
  - worker_nodes  : same shape
  - cp_endpoint   : string (LB public IP)
  - vpc_cidr      : string
  - region        : string

Output:
  all:
    vars:
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/rke2_demo_ed25519
      cp_endpoint: <IP>
      vpc_cidr:    <CIDR>
      region:      <slug>
    children:
      rke2_servers:
        hosts:
          rke2-demo-cp-01:
            ansible_host: <public_ip>
            private_ip:   <private_ip>
            node_role:    control-plane
          ...
      rke2_agents:
        hosts: ...
"""

import argparse
import json
import sys


def emit_host_line(name: str, host: dict) -> list[str]:
    return [
        f"        {name}:",
        f"          ansible_host: {host['public_ip']}",
        f"          private_ip:   {host['private_ip']}",
        f"          node_role:    {host['node_role']}",
    ]


def render(tofu: dict, ssh_key: str, ssh_user: str) -> str:
    cp_nodes = tofu["cp_nodes"]["value"]
    worker_nodes = tofu["worker_nodes"]["value"]
    cp_endpoint = tofu["cp_endpoint"]["value"]
    vpc_cidr = tofu["vpc_cidr"]["value"]
    region = tofu["region"]["value"]

    lines: list[str] = [
        "---",
        "# Generated by ansible/scripts/render-inventory.py.",
        "# Do not edit by hand -- changes will be overwritten on the next `make inventory`.",
        "all:",
        "  vars:",
        f"    ansible_user: {ssh_user}",
        f"    ansible_ssh_private_key_file: {ssh_key}",
        f"    cp_endpoint: {cp_endpoint}",
        f"    vpc_cidr:    {vpc_cidr}",
        f"    region:      {region}",
        "  children:",
        "    rke2_servers:",
        "      hosts:",
    ]
    for node in cp_nodes:
        node = dict(node, node_role="control-plane")
        lines.extend(emit_host_line(node["name"], node))

    lines += [
        "    rke2_agents:",
        "      hosts:",
    ]
    for node in worker_nodes:
        node = dict(node, node_role="worker")
        lines.extend(emit_host_line(node["name"], node))

    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description="Render Ansible inventory from `tofu output -json`.")
    p.add_argument("input", nargs="?", help="Path to `tofu output -json` file. Reads stdin if omitted.")
    p.add_argument(
        "--key",
        default="~/.ssh/rke2_demo_ed25519",
        help="Operator SSH private key path (default: %(default)s).",
    )
    p.add_argument(
        "--user",
        default="root",
        help="SSH user. DO Ubuntu droplets default to root (default: %(default)s).",
    )
    args = p.parse_args()

    raw = open(args.input).read() if args.input else sys.stdin.read()
    tofu = json.loads(raw)
    sys.stdout.write(render(tofu, args.key, args.user))
    return 0


if __name__ == "__main__":
    sys.exit(main())
