#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Render an Ansible YAML inventory from `tofu output -json`.

Consumes stdin (or a file path argument) and prints inventory YAML to stdout.
Stdlib only -- no PyYAML, hand-emitted YAML so we don't need a venv.

Expected Tofu outputs (from terraform/environments/do-test/outputs.tf):
  - cp_nodes                : list({ name, public_ip, private_ip, id })
  - worker_nodes            : same shape
  - cp_endpoint             : string (LB public IP)
  - vpc_cidr                : string
  - region                  : string
  - worker_longhorn_devices : map(string)  -- hostname -> stable /dev/disk/by-id path
                              for the dedicated Longhorn volume per worker.
                              Each per-worker entry becomes a `longhorn_device`
                              host_var consumed by the `longhorn_disk_prep`
                              Ansible role. Required for the enable-longhorn
                              workflow; absent on pre-add-do-block-storage Tofu
                              state, which makes longhorn_device unset and the
                              role's first task `stat: <missing>` fail loudly.

Output:
  all:
    vars:
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/do_nyc3_rke2_demo_ed25519
      cp_endpoint: <IP>
      vpc_cidr:    <CIDR>
      region:      <slug>
    children:
      rke2_servers:
        hosts:
          do-nyc3-rke2-demo-cp-01:
            ansible_host: <public_ip>
            private_ip:   <private_ip>
            node_role:    control-plane
          ...
      rke2_agents:
        hosts:
          do-nyc3-rke2-demo-worker-01:
            ansible_host:    <public_ip>
            private_ip:      <private_ip>
            node_role:       worker
            longhorn_device: /dev/disk/by-id/scsi-0DO_Volume_<name>
          ...
"""

import argparse
import json
import sys


def emit_host_line(name: str, host: dict, longhorn_device: str | None = None) -> list[str]:
    lines = [
        f"        {name}:",
        f"          ansible_host:    {host['public_ip']}",
        f"          private_ip:      {host['private_ip']}",
        f"          node_role:       {host['node_role']}",
    ]
    if longhorn_device is not None:
        lines.append(f"          longhorn_device: {longhorn_device}")
    return lines


def render(tofu: dict, ssh_key: str, ssh_user: str) -> str:
    cp_nodes = tofu["cp_nodes"]["value"]
    worker_nodes = tofu["worker_nodes"]["value"]
    cp_endpoint = tofu["cp_endpoint"]["value"]
    vpc_cidr = tofu["vpc_cidr"]["value"]
    region = tofu["region"]["value"]

    # `worker_longhorn_devices` is optional -- it appears in Tofu output only
    # after the add-do-block-storage substrate work. Pre-substrate state has
    # this key missing entirely (KeyError); we render workers without a
    # longhorn_device host_var in that case, and the longhorn_disk_prep
    # role will fail loudly via its first `stat` task. Cleaner failure
    # than rendering an empty/wrong path.
    worker_longhorn_devices = tofu.get("worker_longhorn_devices", {}).get("value", {})

    lines: list[str] = [
        "---",
        "# Generated by ansible/scripts/render-inventory.py.",
        "# Do not edit by hand -- changes will be overwritten on the next `make inventory`.",
        "all:",
        "  vars:",
        f"    ansible_user: {ssh_user}",
        f"    ansible_ssh_private_key_file: {ssh_key}",
        f"    cp_endpoint: {cp_endpoint}",
        f"    vpc_cidr:    {vpc_cidr}",
        f"    region:      {region}",
        "  children:",
        "    rke2_servers:",
        "      hosts:",
    ]
    for node in cp_nodes:
        node = dict(node, node_role="control-plane")
        lines.extend(emit_host_line(node["name"], node))

    lines += [
        "    rke2_agents:",
        "      hosts:",
    ]
    for node in worker_nodes:
        node = dict(node, node_role="worker")
        lh_device = worker_longhorn_devices.get(node["name"])
        lines.extend(emit_host_line(node["name"], node, lh_device))

    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description="Render Ansible inventory from `tofu output -json`.")
    p.add_argument("input", nargs="?", help="Path to `tofu output -json` file. Reads stdin if omitted.")
    p.add_argument(
        "--key",
        default="~/.ssh/do_nyc3_rke2_demo_ed25519",
        help="Operator SSH private key path (default: %(default)s).",
    )
    p.add_argument(
        "--user",
        default="root",
        help="SSH user. DO Ubuntu droplets default to root (default: %(default)s).",
    )
    args = p.parse_args()

    raw = open(args.input).read() if args.input else sys.stdin.read()
    tofu = json.loads(raw)
    sys.stdout.write(render(tofu, args.key, args.user))
    return 0


if __name__ == "__main__":
    sys.exit(main())
