apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-dns
    namespace: external-dns
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:HPHow6GOQkq5HIrA0rDUYHXhnrGUBCcOogP3byrfPTNC8rHrjHEJHM2s7V1dbIi0UN8jhQLu+qqr4ZdJ+b6G/qRHkYuBtkA=,iv:d0rglBt44e1hLR6qg7tGHRcmhAdDwhi2FtEKKGjOCoY=,tag:es46UCLvCEYXgcpZr6mVUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUGJsYU51RUpLZ0pveUNj
            M0NJT3FnYnVBR21CTll4d1EzMEY2ZUlWbEVrCll6SmUvTjUvS1JtU2dNRTNzTVdi
            U0NTR0hCcTEzVmF0cndxeGlQenNuNDgKLS0tIDM4MnVTZ0tscVpPQlRiQlZiWFlR
            V3NkSDZCeGUzQ2l6WkFaeUREMUNJbU0K4H7lozf28tBwKU6FnR9QjY9y2D38PMlk
            G6Hu3iGyAdg3fGKngcEt/lIdU3m0TuBqYQQ5XHKAlM5hFaIznlorGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s8ed4qr4k7hvwu6mx5z80prurzz2wcq4gk2ujyh8w75ssaxy44xq8pzjdk
    encrypted_regex: ^(data|stringData|.*[Pp]assword|.*[Ss]ecret|.*[Tt]oken|.*[Kk]ey)$
    lastmodified: "2026-05-15T05:00:27Z"
    mac: ENC[AES256_GCM,data:VrLv6npCes4Rb94mZ/2DWgms9nLOiY/fmuuGB9E7tNxbGcuFv7xNpSpjeDp2vbsccdRMoEp4UaXbO7/jnta+JD0oyaIgeZfBVuVGk5PVzuOCOtlNdGFflQU7QdZVGjABtXEnPjwxl796FQaNPGpVt++CsvvDQvSPN0Ssf+dbCDg=,iv:gzJEjyzWZ4LHPEOhqhLr/mSzT15LbW0Zqdl0bNgwScU=,tag:eSsz095QzHf46xWOPu+Mbg==,type:str]
    version: 3.13.0
