# dyff between <(yq . <(helm show values external-dns/external-dns --version v1.20.0)) <(yq eval '. * load("values.yaml")' <(helm show values external-dns/external-dns --version v1.20.0))
# vim -O <(helm show values external-dns/external-dns --version v1.20.0) values.yaml

# In larger environments with lots of records, the default of 1m can trigger rate limiting on Route 53. Uncomment this if needed.
interval: 10m

# If we have a larger interval, we don't want to wait for external-dns to make changes. Uncomment this if needed.
triggerLoopOnEvent: true

# We want to delete records for ingresses that have been deleted.
policy: sync

# If we have multiple k8s clusters writing to the same DNS zone, each external-dns needs a way to identify the records it owns. And since we can only have one external-dns provider per cluster, the setting this to the cluster name seems reasonable.
txtOwnerId: project1-dev

# Cloudflare config based on:
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
provider:
  name: cloudflare
  webhook:
    args:
      - --cloudflare-dns-records-per-page=5000
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

resources:
  requests:
    cpu: 32m
    memory: 100Mi
  limits:
    # Can't explicitly set this to null, because the helm chart is a little overengineered...
    # "resources.limits.cpu: Invalid type. Expected: string, given: null"
    memory: 100Mi
