---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cert-manager-custom-resources.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - imagepolicies.yaml
  - imagerepositories.yaml
  - imageupdateautomation.yaml
  - ingress-nginx.yaml
  - sops-age.secrets.yaml
  - digitalocean-cloud-controller-manager.yaml
patchesStrategicMerge:
  - flux-resources-patch.yaml
