apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:zJZrUBVVo/Ii2BEXzgrAB3bP02ou4DHWlsPb686LA3pBB1PwAoM7d+D3bgfgo+59V7DBohUaEp8jT4/HwP3xmot4o6V+hxlJ3f/Hx4NMiQVpzp8XiHgYvfmEpNWbdHvZrdtdeS6zj0zuJrV5vOFl4tpkoF5e5N3k1S6P/EzfhSx3OIorJoRpyYKOOMNSURz5GovWYiFOPr/9Cdfpi4epeJt0vJr4V9mu1rL2PprudLCnOwZGRjW4kna4rmW5,iv:uzrDpP+mqHc22uZ13TxS68o7wFGIQN66H1lmnF78/EA=,tag:tPqeRG/+/RwMMQza/3vx8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraGhJaUd1MmIrNlduWkZJ
            WUZxRlVkQmc4YVByL1ZIaTdXQ1VPL2ZQcWhVCkFBMTdqQXpyUHM4blV1ZU1HaWFB
            NVlhUXZWd2htRmhQdkxBcUVMcnU3OFkKLS0tIEtVSkFTUExtMFFqTVErdUVjajI0
            N2t6amVvQnFMSzhHM08zTGVKd0pCTkkKDLmRQb8XWIhXD3ZDhYuObsgPbponXSD4
            ROXey3bcrrYnGOvah5H7hVMzk5cpeHNvMUwQiQR4TUSPe2ZP2MkM/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s8ed4qr4k7hvwu6mx5z80prurzz2wcq4gk2ujyh8w75ssaxy44xq8pzjdk
    encrypted_regex: ^(data|stringData|.*[Pp]assword|.*[Ss]ecret|.*[Tt]oken|.*[Kk]ey)$
    lastmodified: "2026-05-15T05:36:54Z"
    mac: ENC[AES256_GCM,data:Q/xtu4DjYZ6rA7SUcyHmfvRfuspwYEEzLR/9094tluvviITqV/M3XlNlQ6oMXkBga+AJz4nLqVdmdRy2vCnQofKSBPgCU+tQZHgigBm3DyNANDAunI8nyWFZXg+Zd6HKXGFIy46Z2BN0+GrwKbUpZyguq5ORm3fFquWDwno6aII=,iv:mzUzHRuGGIZlQLcoxdg3Omvd64eoP9o5+f0y9MsqGEg=,tag:kiQkJr9Qok4Nx4jSFLKSVg==,type:str]
    version: 3.13.0
