apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-dns
    namespace: cert-manager
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:S2k7BGZeMnohELOZXYYJJ4kTaKS4Vy6A8KJ0euMa6cARKDWawIWmwY1ACPwW60ID9K7DtFf1MLkXRafeLEukK5wY+9jF3ig=,iv:yQBSI5+6MgrxYEcwogHaw7m0qbdJad/KHUodS2I/k1E=,tag:XPukKgEsKNij5zP4bX6zdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeUZnRVIvMmNkdE1tZ2M0
            Tm1PQW5RVjlFdjJtbmpFRGFmVGEwRGhDSVc0CkJPVG9BWUVxWS94NnJkNXpCU3lj
            S2lNbGg4bTdiRlUvdzU1TWpmMjF2YmcKLS0tIDY4ZVhjRjZ5NmV3KzB6Y1Bab3hS
            ZHBOK3hNRWZoU2JIcVdtTjVBSlBwRFEKGO4fJA5VveXgUYDbiLm0djxZKYp/sLcv
            FdUQ8LVyv8Zy38pvFhaVoIuKEcfNUmAFCiZ9CWA0jxYATrSwAkeNYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s8ed4qr4k7hvwu6mx5z80prurzz2wcq4gk2ujyh8w75ssaxy44xq8pzjdk
    encrypted_regex: ^(data|stringData|.*[Pp]assword|.*[Ss]ecret|.*[Tt]oken|.*[Kk]ey)$
    lastmodified: "2026-05-15T05:00:27Z"
    mac: ENC[AES256_GCM,data:FAHWyXUO5mLDfG4K1EYOY6SdbOzDjTuF/UWiT1gXPOPPr5JE5fNihs5E7XnA8MYyqwy0TQo7qzxek5Lkug3NlUNPQluEgaWXmB4JrP+7LPuKe318ATl219Fz73Jxku+t4SpsRs30vZKURBVnAH9Jbir5cspRcq6KgsYQJdU0T3g=,iv:998taOqIfNI0yWKG/Z3Pmnh9nMnwbV5bMXfOnlDRqBo=,tag:b/+GVhgqRkic3GEWTTdYew==,type:str]
    version: 3.13.0
