rke2_server_token: ENC[AES256_GCM,data:qp4rS37RQPATYFIjc6yhYCbEyH9lWhuBFFohQf7KcIeRsNn5ih4uDgUzhKUqtjHLpRcxWjyLfg5BweZJcCbdKg==,iv:vacCjnzSneMN2xSp/o/B/xSsPhaZoTTrPjLKv9ChINU=,tag:wSMqJkdx1LbPStG0smbC0g==,type:str]
rke2_agent_token: ENC[AES256_GCM,data:KrJyIOBICRtYrqx7qoU3gkL7NaQXIXjWHVGzG6IfCzznjPP/s+DR34MiJYRQ1jhhBCQHJlAJ2VT5KrGnEe/4dg==,iv:FOpYP7NQyEjByuVP8ZfXa/oywRxt+adFGlVdTyszprQ=,tag:8un1szA/4PBgUn0Y1yUQ9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcVRyK2lOYnAvSlZzNUxj
            Y1ZSWU54KzArY0JqaUQyd3JCbnpCNHhYa1hrCm40TjhSVGYyS09EUFQzNzVDNmtl
            YzF5cHZwTzNoOC9qbURUWUh2YVlMb2cKLS0tIHRhM3ZtN2VSYmphNnBNTTNwdjhD
            OUdlU2RzNCtReHp4eUsxL3E3K2tGcFUKjBsOSadHURxboV4uxpJQJeTC246b4bCa
            02PmlHkXeYHVmSMewuDEhusThOngLG6M/UafU5TzWc8Oee717LLNcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s8ed4qr4k7hvwu6mx5z80prurzz2wcq4gk2ujyh8w75ssaxy44xq8pzjdk
    encrypted_regex: ^(data|stringData|.*[Pp]assword|.*[Ss]ecret|.*[Tt]oken|.*[Kk]ey)$
    lastmodified: "2026-05-14T22:52:37Z"
    mac: ENC[AES256_GCM,data:qBI+O8hTWDEE9cMC8lOgql/KcPCwsfQsdt/x/XrZh80f5WKenGYVAYB9Waw+iPQS2O3UqHp1vT/JMd55+0gM4VsFskgKi4h/Mx3/FfSQFza0Yj6L2U5vNO/M0UAufQkC/5uRmT7FIqpCWmh6dF0NkbN3IgZUEPrOMJeZmrYQELw=,iv:9UOZ3i7hX4DYi5zgjdQe2wCbFlrtcul4VaIAhbTTkzk=,tag:mwtE5qZfQydxBjJZYTjg0w==,type:str]
    version: 3.13.0
