sops:
    age:
        - recipient: age1s8ed4qr4k7hvwu6mx5z80prurzz2wcq4gk2ujyh8w75ssaxy44xq8pzjdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MTZaTkhOVk9nVXJlTzIz
            emE4M0xpUForRTNDaSs0dGx4R2tCWE5LbGdnCjFOZ0VLdCtWZGJkL1VIaDFhRGlU
            MTg1MGI3a1FBZ3dTUVR4dTMwalNiZ3cKLS0tIEwvejN4czFheWJFRlFmL3ZUQzlB
            RENMRTkyZjQ4ekEreEd2TGhOSU1vdEUKvI3snX36gbaHaYKN0VpVsYkmy10jW1UT
            NMes8Qmnc91Qgn+M1Sm6NBFSP3fV+QF0w7ss1WFOmutKyOYRXnbytw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T06:21:04Z"
    mac: ENC[AES256_GCM,data:QgqbB+ZmQ6WF6Rm9b/+MifQx4IUqKPHqziwXGyAbU0Veszxnzd3ajtunYV1jRaXmDjUCglPKzId5TUvsZFB2rQovgJ8dmV/8CO7GcVa0tFpRtJn1B+NbiENQZaj4qbp3p3vA8sGJWI961M9M3UhKQmNn1FuW1wpz0EBLmS+3xic=,iv:MkLXrcWxvvz/z4V0lAkDc7WID+0cJzymeTBpHpvQ1oE=,tag:D8rilaR3QWVIgDVY4qbaDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
